//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace blackWood.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietSP
    {
        public string id { get; set; }
        public string MaSP { get; set; }
        public string MaNSX { get; set; }
        public Nullable<double> Gia { get; set; }
    
        public virtual NuocSX NuocSX { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
