//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace blackWood.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanHoi
    {
        public string MaPH { get; set; }
        public string NoiDung { get; set; }
        public string TenNguoiPH { get; set; }
        public Nullable<System.DateTime> ThoiGianPH { get; set; }
        public string MaSP { get; set; }
    
        public virtual SanPham SanPham { get; set; }
    }
}
