//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace blackWood.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.AnhSPs = new HashSet<AnhSP>();
            this.ChiTietDDHs = new HashSet<ChiTietDDH>();
            this.ChiTietSPs = new HashSet<ChiTietSP>();
            this.PhanHois = new HashSet<PhanHoi>();
        }
    
        public string MaSP { get; set; }
        public string TenSP { get; set; }
        public string MaMau { get; set; }
        public string MaKT { get; set; }
        public string GioiThieu { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public string MaLoai { get; set; }
        public Nullable<int> SoLuongTon { get; set; }
        public string AnhSP { get; set; }
        public Nullable<double> DonGia { get; set; }
        public string MaNSX { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnhSP> AnhSPs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDDH> ChiTietDDHs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietSP> ChiTietSPs { get; set; }
        public virtual KichThuoc KichThuoc { get; set; }
        public virtual LoaiSp LoaiSp { get; set; }
        public virtual Mau Mau { get; set; }
        public virtual NuocSX NuocSX { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhanHoi> PhanHois { get; set; }
    }
}
